### ISSUE TITLE
Epic: Profile Management

### ISSUE THREAD

**Issue by behemot-biz** [behemot-biz/tastyslask#102]
### Tasks under this Epic:

- [x] #7 Implement View Profile API endpoint
- [x] #8 Implement View Profile Details API endpoint
- [x] #9 Implement Update Profile Details API endpoint

**Goal**: Enable users to view and update profiles
